CREATE DATABASE [NonProd_Test] ON  PRIMARY 
( NAME = N'NonProd_Test', FILENAME = N'I:\SQLServer\Data\NonProd_Test.mdf' , SIZE = 1048576KB , FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'NonProd_Test_log', FILENAME = N'J:\SQLServer\Log\NonProd_Test_log.ldf' , SIZE = 524288KB , FILEGROWTH = 524288KB )
GO
ALTER DATABASE [NonProd_Test] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [NonProd_Test] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NonProd_Test] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NonProd_Test] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NonProd_Test] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NonProd_Test] SET ARITHABORT OFF 
GO
ALTER DATABASE [NonProd_Test] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NonProd_Test] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NonProd_Test] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [NonProd_Test] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NonProd_Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NonProd_Test] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NonProd_Test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NonProd_Test] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NonProd_Test] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NonProd_Test] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NonProd_Test] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NonProd_Test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NonProd_Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NonProd_Test] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NonProd_Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NonProd_Test] SET  READ_WRITE 
GO
ALTER DATABASE [NonProd_Test] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NonProd_Test] SET  MULTI_USER 
GO
ALTER DATABASE [NonProd_Test] SET PAGE_VERIFY CHECKSUM  
GO
USE [NonProd_Test]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [NonProd_Test] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
